server:
  port: 8037

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1041197191@qq.com
    password: bohgpwdddqrmbdej
    port: 465
    properties:
      mail:
        smtp:
          auth: true

